### ISSUE TITLE
Add secp256r1 signature support

### ISSUE THREAD

**Issue by aaronc** [cosmos-cg-key-management/cosmos-sdk#17]
Also known as NIST P-256. See https://github.com/cosmos/cosmos-sdk/issues/4789

**Comment by aaronc** [comment]
Note support for this is already in the go crypto library as Zaki mentioned: https://golang.org/src/crypto/elliptic/elliptic.go?s=11372:11389#L368

**Comment by aaronc** [comment]
@sahith-narahari is this something you could work on? Let's discuss.

**Comment by sahith-narahari** [comment]
We shall proceed by implementing pubkey interface for nist p-256. Future steps would be to figure a way to get address from pubkey.
 To be discussed is how we can get this implementation for encoding either using protobuf directly or amino.

### Useful links 
https://golang.org/pkg/crypto/elliptic/#P256
https://golang.org/pkg/crypto/ecdsa/

**Comment by sahith-narahari** [comment]
We shall proceed by implementing pubkey interface for nist p-256. Future steps would be to figure a way to get address from pubkey.
 To be discussed is how we can get this implementation for encoding either using protobuf directly or amino.

### Useful links 
https://golang.org/pkg/crypto/elliptic/#P256
https://golang.org/pkg/crypto/ecdsa/

**Comment by clevinson** [comment]
@aaronc please add me to the key mgmt group so I can track this ticket in codetree.

**Comment by clevinson** [comment]
@sahith-narahari can you tag @aaronc as a reviewer in a WIP PR so we can take a look at this?

**Comment by sahith-narahari** [comment]
Sure @clevinson , will raise a draft PR and tag

**Comment by sahith-narahari** [comment]
https://github.com/cosmos/cosmos-sdk/pull/5878 @aaronc can you take a lot at this, I'm stuck at creating public from secp256r1.
Also which random generator can I use for creating sign bytes

**Comment by aaronc** [comment]
@sahith-narahari where do you need a random generator?

**Comment by robert-zaremba** [comment]
Is this task still on? we are doing it in SDK
