### ISSUE TITLE
Msg authorization --send-as CLI flag implementation

### ISSUE THREAD

**Issue by aaronc** [cosmos-cg-key-management/cosmos-sdk#27]
# Acceptance Criteria

- [ ] implement the `--send-as` flag in the [cosmos-sdk client package](https://github.com/cosmos/cosmos-sdk/tree/master/client) as specified here: https://github.com/cosmos-cg-key-management/cosmos-sdk/blob/regen-network/msg-delegation-spec/docs/architecture/adr-013-msg-authorization.md#--send-as-flag
- [ ] integration tests? (is this realistic @ethanfrey?)

**Comment by ethanfrey** [comment]
Integration tests are realistic, but maybe not automated. There should at least be a simple walk-through as we did in the gaia upgrade run, that is checked manually during execution phase.

The `--send-as` flag must be registered as a global flag on `gaiacli tx`, and processed in the generic tx logic, for it to work as you mentioned. This then makes a hard link between `cosmos-sdk/client` and `x/msg_authorization/` which may be circular (as `x/msg_authorization/client/cli` imports `cosmos-sdk/client`) and in any case likely unpalatable to the sdk team.

I am not sure of any alternative approach however, given the current tx monolith architecture. But maybe a deeper dive into it may provide some hook to allow this, at least on the app level. (Just to explain an alternative that may give inspiration, look at [a sample bnscli script](https://github.com/iov-one/weave/blob/master/cmd/bnscli/clitests/gov_update-electorate.test) from weave. There are atomic commands piped together. In this case `update-electorate` creates a msg, `with-elector` can be called multiple times to add more electors (which could also be done with a list on the first argument), but most importantly *bnscli as-proposal* will take the existing message (formed from any commands) and use it as the payload of another message (gov vote).

This same approach could be applied here, just pipe the output into a script that embeds the message. However, this does imply that there is a clear separation between constructing a message, signing it, and submitting it.

I would propose a spike to investigate viable alternatives here
