### ISSUE TITLE
Agree on ORM spec

### ISSUE THREAD

**Issue by aaronc** [cosmos-cg-key-management/cosmos-sdk#28]

**Comment by clevinson** [comment]
Current draft ORM spec: https://gist.github.com/aaronc/11033894183b770ccd8cd5d24c30e615

**Comment by clevinson** [comment]
@aaronc is this spec agreed on? If not, what stakeholders are necessary to sign off on this spec? I'm happy to wrangle folks necessary and try to push this through if it just needs eyeballs from a few people.

**Comment by aaronc** [comment]
Yes, it's implemented!

**Comment by clevinson** [comment]
@aaronc can you close this issue ?
