### ISSUE TITLE
Add Daily or Periodic FeeAllowance implementation

### ISSUE THREAD

**Issue by aaronc** [cosmos-cg-key-management/cosmos-sdk#5]

**Comment by ethanfrey** [comment]
This seems like the relevant PR that needs finishing. To make this more clear:
https://github.com/cosmos/cosmos-sdk/pull/4616

Is there a spec of this? Or just clean up according to comments?

**Comment by ethanfrey** [comment]
Wait, that is linked here: https://github.com/cosmos-cg-key-management/cosmos-sdk/issues/6

What is the difference between these two issue?
